
export const SongsData = [
    { "id": 1, "videoId": "dQw4w9WgXcQ", "name": "Never Gonna Give You Up", "artist": "Rick Astley", "Genre": "happy" },
    { "id": 2, "videoId": "3JZ_D3ELwOQ", "name": "Uptown Funk", "artist": "Mark Ronson ft. Bruno Mars", "Genre": "happy" },
    { "id": 3, "videoId": "lDK9Q7Iig9A", "name": "I Gotta Feeling", "artist": "The Black Eyed Peas", "Genre": "happy" },
    { "id": 4, "videoId": "6eZg7COGZSA", "name": "Shape of You", "artist": "Ed Sheeran", "Genre": "happy" },
    { "id": 5, "videoId": "fJ9rUzIMcZQ", "name": "Bohemian Rhapsody", "artist": "Queen", "Genre": "happy" },
    { "id": 6, "videoId": "J---aiyznGQ", "name": "Despacito", "artist": "Luis Fonsi ft. Daddy Yankee", "Genre": "happy" },
    { "id": 7, "videoId": "YbJOTdZBX1s", "name": "Old Town Road", "artist": "Lil Nas X", "Genre": "happy" },
    { "id": 8, "videoId": "pA3H9EqFfWU", "name": "Bad Guy", "artist": "Billie Eilish", "Genre": "happy" },
    { "id": 9, "videoId": "N4Udo3LPB2s", "name": "Blinding Lights", "artist": "The Weeknd", "Genre": "happy" },
    { "id": 10, "videoId": "s4zBQUhSE64", "name": "Levitating", "artist": "Dua Lipa", "Genre": "happy" },
    { "id": 11, "videoId": "M9FJj5ftNTw", "name": "Watermelon Sugar", "artist": "Harry Styles", "Genre": "sad" },
    { "id": 12, "videoId": "7CqQJQU6j70", "name": "Drivers License", "artist": "Olivia Rodrigo", "Genre": "sad" },
    { "id": 13, "videoId": "djV11Xbc914", "name": "All About That Bass", "artist": "Meghan Trainor", "Genre": "sad" },
    { "id": 14, "videoId": "fL9S3IV6w5Q", "name": "Good 4 U", "artist": "Olivia Rodrigo", "Genre": "sad" },
    { "id": 15, "videoId": "p6kKZzD2-Ks", "name": "Roar", "artist": "Katy Perry", "Genre": "sad" },
    { "id": 16, "videoId": "xwtdhWltz2Y", "name": "Happy", "artist": "Pharrell Williams", "Genre": "sad" },
    { "id": 17, "videoId": "e1d8z0Ohf3E", "name": "Rolling in the Deep", "artist": "Adele", "Genre": "sad" },
    { "id": 18, "videoId": "aL6MSyS3ShQ", "name": "Can't Stop the Feeling!", "artist": "Justin Timberlake", "Genre": "sad" },
    { "id": 19, "videoId": "kJQP7kiw5Fk", "name": "Despacito", "artist": "Luis Fonsi ft. Daddy Yankee", "Genre": "sad" },
    { "id": 20, "videoId": "a1E18RlbEY0", "name": "Dynamite", "artist": "BTS", "Genre": "sad" },
    { "id": 21, "videoId": "xXHswCkn9L4", "name": "Someone Like You", "artist": "Adele", "Genre": "fearful" },
    { "id": 22, "videoId": "Wf7Ap0yxM9E", "name": "Shallow", "artist": "Lady Gaga & Bradley Cooper", "Genre": "fearful" },
    { "id": 23, "videoId": "cA7FCjOd8zo", "name": "Perfect", "artist": "Ed Sheeran", "Genre": "fearful" },
    { "id": 24, "videoId": "0WXJ6q5n8Xs", "name": "Bang Bang", "artist": "Jessie J, Ariana Grande, Nicki Minaj", "Genre": "fearful" },
    { "id": 25, "videoId": "d1dJoGP8UBY", "name": "Uptown Funk", "artist": "Mark Ronson ft. Bruno Mars", "Genre": "fearful" },
    { "id": 26, "videoId": "iL5e7L9mdNo", "name": "Can't Feel My Face", "artist": "The Weeknd", "Genre": "fearful" },
    { "id": 27, "videoId": "5ZdKbAn5o8I", "name": "Say You Won't Let Go", "artist": "James Arthur", "Genre": "fearful" },
    { "id": 28, "videoId": "7-5mbhVgjTk", "name": "Starboy", "artist": "The Weeknd", "Genre": "fearful" },
    { "id": 29, "videoId": "OhED6c6TH6Q", "name": "Havana", "artist": "Camila Cabello ft. Young Thug", "Genre": "fearful" },
    { "id": 30, "videoId": "mYwGm3GfsqE", "name": "Treat You Better", "artist": "Shawn Mendes", "Genre": "fearful" },
    { "id": 31, "videoId": "e6N3o7J2tEk", "name": "Rockstar", "artist": "Post Malone ft. 21 Savage", "Genre": "fearful" },
    { "id": 32, "videoId": "kQd66ApTwx0", "name": "Closer", "artist": "The Chainsmokers ft. Halsey", "Genre": "fearful" },
    { "id": 33, "videoId": "tsc_kYkWE60", "name": "In My Feelings", "artist": "Drake", "Genre": "fearful" },
    { "id": 34, "videoId": "VSFznS0zHBY", "name": "No Tears Left to Cry", "artist": "Ariana Grande", "Genre": "disgusted" },
    { "id": 35, "videoId": "sfWvG08M-FI", "name": "This Is What You Came For", "artist": "Calvin Harris ft. Rihanna", "Genre": "disgusted" },
    { "id": 36, "videoId": "NRK1S7-6D8k", "name": "One Dance", "artist": "Drake ft. Wizkid & Kyla", "Genre": "disgusted" },
    { "id": 37, "videoId": "p2P6X2wU6NI", "name": "Thinking Out Loud", "artist": "Ed Sheeran", "Genre": "disgusted" },
    { "id": 38, "videoId": "TzP4sIs72E4", "name": "Bad Romance", "artist": "Lady Gaga", "Genre": "disgusted" },
    { "id": 39, "videoId": "ZXNMM-dQDHY", "name": "Bleeding Love", "artist": "Leona Lewis", "Genre": "disgusted" },
    { "id": 40, "videoId": "6lPZpZLgJd4", "name": "We Don't Talk Anymore", "artist": "Charlie Puth ft. Selena Gomez", "Genre": "disgusted" },
    { "id": 41, "videoId": "g6T1RbGkvJY", "name": "I Don't Want to Miss a Thing", "artist": "Aerosmith", "Genre": "disgusted" },
    { "id": 42, "videoId": "Q8-tgY5-Sz4", "name": "Hey Ya!", "artist": "OutKast", "Genre": "disgusted" },
    { "id": 43, "videoId": "HXeInR-q4l0", "name": "I Will Always Love You", "artist": "Whitney Houston", "Genre": "disgusted" },
    { "id": 44, "videoId": "Hq7b8sJ6e0Q", "name": "With or Without You", "artist": "U2", "Genre": "disgusted" },
    { "id": 45, "videoId": "c5pKh0T9ZrY", "name": "Sweet Child O' Mine", "artist": "Guns N' Roses", "Genre": "disgusted" },
    { "id": 46, "videoId": "mGoFzIXxCQg", "name": "Someone You Loved", "artist": "Lewis Capaldi", "Genre": "disgusted" },
    { "id": 47, "videoId": "6FJtqRWS9x0", "name": "Don't Let Me Down", "artist": "The Chainsmokers ft. Daya", "Genre": "disgusted" },
    { "id": 48, "videoId": "2S6Fs_g-oGQ", "name": "Happier", "artist": "Marshmello ft. Bastille", "Genre": "disgusted" },
    { "id": 49, "videoId": "z1owtOQwS1E", "name": "Roses", "artist": "SAINt JHN", "Genre": "disgusted" },
    { "id": 50, "videoId": "QodtCqZduH0", "name": "Love Yourself", "artist": "Justin Bieber", "Genre": "disgusted" }
]

